#!/bin/sh
# vim: et sw=2 st=2 ts=2 tw=0:
#
# GUI front end for persistence-wizard-cli
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU  General Public License as published by
# the Free Software Foundation; either version 3 of the License or (at
# your option) any later version.
# Please take a look at http://www.gnu.org/copyleft/gpl.htm
#
# Written by: Cyrille Pontvieux <jrd~at~enialis~dot~net>
# Modified by: Pierrick Le Brun <akuna~at~free~dot~fr>


# Gettext internationalization
export TEXTDOMAIN="persistence-wizard"
export TEXTDOMAINDIR="/usr/share/locale"
. gettext.sh

CLIPRGM=/usr/sbin/persistence-wizard-cli
RWMP=/tmp/persistentwiz-rwmountpoints
if [ -f /mnt/salt/lib/libSaLT ]; then
  . /mnt/salt/lib/libSaLT
else
  ROOT_DIR=salixlive
fi
NAME="$ROOT_DIR.save"
savefilename=$(get_value_cmdline savefile)
[ -n "$savefilename" ] && NAME="$savefilename"
unset savefilename

if [ ! $DISPLAY ]; then
  echo -e "`eval_gettext 'ERROR: $TEXTDOMAIN must be executed within a running X session.\n'`"
  exit 1
fi

if [ "$UID" != "0" ]; then
  echo "`eval_gettext 'ERROR: You need to be root to run'` $(basename $0)"
  exit 1
fi

if [ ! `which zenity` ]; then
  echo "`eval_gettext 'ERROR: zenity must be installed and in your PATH to run'` $(basename $0)"
  exit 1
fi

if [ ! `which mkfs.xfs` ]; then
  echo "`eval_gettext 'ERROR: xfsprogs must be installed to run'` $(basename $0)"
  exit 1
fi

# find possible writable partitions and free size in megabytes
cat /dev/null > $RWMP
tempd=$(mktemp -d)
IFS="
"
for l in $(/sbin/blkid -o list); do
  if [ "${l:0:1}" = "/" ]; then
    device=$(echo "$l"|awk '{print $1;}')
    fs=$(echo "$l"|awk '{print $2;}')
    echo "$fs"|grep -q "^ext." && fs="ext"
    echo "$fs"|grep -q "vfat" && fs="vfat"
    echo "$fs"|grep -q "ntfs" && fs="ntfs"
    if [ "$fs" = "ext" -o "$fs" = "reiserfs" -o "$fs" = "xfs" -o "$fs" = "vfat" -o "$fs" = "ntfs" ]; then
      mp=$(grep "^$device" /etc/mtab|cut -d' ' -f2)
      if [ -z "$mp" ]; then
        mp="$tempd/$(echo "$device"|sed 's:/:_:g')-$fs"
        mkdir -p "$mp"
        if [ "$fs" = "ntfs" ]; then
          mount.ntfs-3g "$device" "$mp"
        else
          mount "$device" "$mp"
        fi
        touch "$mp/_test_rw" 2> /dev/null
        if [ $? -ne 0 ]; then
          umount "$mp"
          rmdir "$mp"
          unset mp
        else
          rm "$mp/_test_rw"
        fi
      else
        touch "$mp/_test_rw" 2> /dev/null
        if [ $? -ne 0 ]; then
          unset mp
        else
          rm "$mp/_test_rw"
        fi
      fi
      if [ -n "$mp" ]; then
        size=$(df -BM -l "$mp"|tail -n1|awk '{print $4}'|tr -d M|rev|sed 's/.\{3\}/\0 /g'|rev)
        echo "$mp:$size" >> $RWMP
      fi
    fi
  fi
done
unset IFS # restore IFS

zenity --info \
 --title "`eval_gettext 'Persistence Wizard'`" \
 --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
 --text "`eval_gettext 'If you wish, you can save any of your work or modification performed while in a LiveCD session.\n\nTo do this however, you must first create a special "persistent file" which will have a pre-determined fixed-size and will be formatted as a linux file system.\n\nOnce this file is created, simply reboot the LiveCD for your changes to become persistent from then on.'`"

IFS=":
"
MOUNTPOINT=$(zenity \
  --title "`eval_gettext 'Mount point selection'`" \
  --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
  --list \
  --text "`eval_gettext 'Choose the mountpoint where the persistent file must be created:'`" \
  --column "`eval_gettext 'Mount point'`" \
  --column "`eval_gettext 'Size (in MB)'`" \
  $(cat $RWMP))
unset IFS

if [ -z "$MOUNTPOINT" ]; then
  rm -f $RWMP
  zenity \
    --title "`eval_gettext 'Error'`" \
    --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
    --error \
    --text "`eval_gettext 'No partition was selected. The program will stop now!'`"
  find $tempd -type d -mindepth 1 -exec umount '{}' \;
  rm -rf $tempd
  exit 1
fi

MAXSIZE=$(grep ^"$MOUNTPOINT:" $RWMP|cut -d: -f2|tr -d ' ')
DEFSIZE=$((MAXSIZE - 250)) # so there is still 250 MB remaining on the partition
if [ $DEFSIZE -gt 500 ]; then # 500 MB max for default size
  DEFSIZE=500
fi

export MOUNTPOINT MAXSIZE

SIZE=$(zenity \
  --title "`eval_gettext 'Size selection'`" \
  --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
  --entry \
  --text "`eval_gettext 'Set the size in megabytes (maximum $MAXSIZE) for persistent file on $MOUNTPOINT:'`" \
  --entry-text $DEFSIZE)

if [ -z "$SIZE" ]; then
  rm -f $RWMP
  zenity \
    --title "`eval_gettext 'Error'`" \
    --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
    --error \
    --text "`eval_gettext 'No size was set. The program will stop now!'`"  
  find $tempd -type d -mindepth 1 -exec umount '{}' \;
  rm -rf $tempd
  exit 1

export SIZE
  
elif [ $SIZE -gt $MAXSIZE ]; then
  rm -f $RWMP
  zenity \
    --title "`eval_gettext 'Error'`" \
    --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
    --error \
    --text "`eval_gettext 'The chosen size exceeds the available place ($SIZE > $MAXSIZE). The program will stop now!'`"
  find $tempd -type d -mindepth 1 -exec umount '{}' \;
  rm -rf $tempd
  exit 1
fi

FORMAT=$(zenity \
--height=280 \
  --title "`eval_gettext 'File system selection'`" \
  --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
  --list \
  --text "`eval_gettext 'Select the file system that will be used to format your persistent file:'`" \
  --radiolist \
  --column "Select"  --column "File system" \
  FALSE xfs \
  TRUE ext2 \
  FALSE ext3 \
  FALSE ext4 \
  FALSE reiserfs \
  FALSE vfat \
  FALSE ntfs)

if [ -z "$FORMAT" ]; then
  rm -f $RWMP
  zenity \
    --title "`eval_gettext 'Error'`" \
    --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
    --error \
    --text "`eval_gettext 'No file system was selected. The program will stop now!'`"
  find $tempd -type d -mindepth 1 -exec umount '{}' \;
  rm -rf $tempd
  exit 1
fi

export FORMAT

SAVEDIR="$MOUNTPOINT/$ROOT_DIR/persistence"
if [ ! -d "$SAVEDIR" ]; then
	mkdir -p "$SAVEDIR"
fi
if [ -d /mnt/salt ]; then
  DEVICE=$(mount | grep " on $MOUNTPOINT " | sed 's/\(.*\) on .*/\1/')
  export DEVICE
fi

cd $SAVEDIR

(yes | zenity --progress --pulsate --auto-close --auto-kill) &
$CLIPRGM $NAME $SIZE $FORMAT
ret=$?
killall yes

cd -
sync
find $tempd -type d -mindepth 1 -maxdepth 1 -exec umount '{}' \;
rm -rf $tempd
rm -f $RWMP
if [ $ret -eq 0 ]; then
  zenity \
    --title "$TEXTDOMAIN" \
    --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
    --info \
    --text "`eval_gettext '$NAME ($SIZE MB) correctly created in $SAVEDIR with $FORMAT file system.'`"
  if [ -n "$DEVICE" ]; then
    echo "$DEVICE:$ROOT_DIR/persistence/$NAME" > /mnt/salt/sync-persistence
  fi
  exit 0
else
  rm -f $RWMP
  zenity \
    --title "`eval_gettext 'Error'`" \
    --window-icon /usr/share/icons/hicolor/128x128/apps/persistence-wizard.png \
    --error \
    --text "`eval_gettext 'Something went wrong! $NAME ($SIZE MB) cannot be created in $SAVEDIR.'`"
  exit 1
fi
